//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDoCauCa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CTHoaDon
    {
        [DisplayName("Mã chi tiết hóa đơn")]
        public int MaCTHD { get; set; }
        [DisplayName("Mã hóa đơn")]
        public int MaHD { get; set; }
        [DisplayName("Mã sản phẩm")]
        public int MaSP { get; set; }
        [DisplayName("Số lượng")]
        public int SoLuong { get; set; }
    }
}
