//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDoCauCa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Hang
    {
        [DisplayName("Mã hãng")]
        public int MaHang { get; set; }
        [DisplayName("Tên hãng")]
        public string TenHang { get; set; }
        [DisplayName("Hình ảnh")]
        public string HinhAnh { get; set; }
    }
}
