//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDoCauCa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class HoaDon
    {
        [DisplayName("Mã hóa don")]
        public int MaHD { get; set; }
        [DisplayName("Tên tài kho?n")]
        public string TenTK { get; set; }
        [DisplayName("Ngày bán")]
        public string NgayBan { get; set; }
        [DisplayName("Ð?a ch?")]
        public string DiaChi { get; set; }
        [DisplayName("SÐT")]
        public string SDT { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
