//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDoCauCa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TaiKhoan
    {
        [DisplayName("Tên tài khoản")]
        public string TenTK { get; set; }

        [DisplayName("Mật khẩu")]
        public string MatKhau { get; set; }
        [DisplayName("Họ tên")]
        public string HoTen { get; set; }
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
        [DisplayName("Số điện thoại")]
        public string SDT { get; set; }
    }
}
